### ISSUE TITLE
Missing data files, or not generated for Linux build

### ISSUE THREAD

**Issue by burger-drip** [alariq/mc2srcdata#1]
Hi,

I've compiled the mc2 build and tools.
I've copied over tools to `build_tools` and run these successfully.

I've also been a little confused about the two texture locations. 
 - `mc2srcdata/build_scripts/data/textures`, and
 - `mc2srcdata/textures`

Initially, I copied the folder contents from `mc2srcdata/textures` --> `mc2srcdata/build_scripts/data/textures`

For the binary mc2. I created a bin directory and symlinked the data as so:
```
$ tree 
.
├── art.fst -> ../../mc2srcdata/build_scripts/art.fst
├── assets -> ../../mc2srcdata/build_scripts/assets
├── camera.fst -> ../../mc2srcdata/build_scripts/camera.fst
├── data -> ../../mc2srcdata/build_scripts/data
├── effect.fst -> ../../mc2srcdata/build_scripts/effect.fst
├── h2prefs1.cfg -> ../../mc2srcdata/build_scripts/h2prefs1.cfg
├── h2prefs.cfg -> ../../mc2srcdata/build_scripts/h2prefs.cfg
├── hiprefs1.cfg -> ../../mc2srcdata/build_scripts/hiprefs1.cfg
├── hiprefs.cfg -> ../../mc2srcdata/build_scripts/hiprefs.cfg
├── insignia.fst -> ../../mc2srcdata/build_scripts/insignia.fst
├── libmc2res.so -> ../libmc2res.so
├── mc2 -> ../mc2
├── midprefs1.cfg -> ../../mc2srcdata/build_scripts/midprefs1.cfg
├── midprefs.cfg -> ../../mc2srcdata/build_scripts/midprefs.cfg
├── minprefs1.cfg -> ../../mc2srcdata/build_scripts/minprefs1.cfg
├── minprefs.cfg -> ../../mc2srcdata/build_scripts/minprefs.cfg
├── misc.fst -> ../../mc2srcdata/build_scripts/misc.fst
├── mission.fst -> ../../mc2srcdata/build_scripts/mission.fst
├── options.cfg
├── orgprefs.cfg
├── prefs.cfg -> ../../mc2srcdata/build_scripts/prefs.cfg
├── shaders -> ../shaders
├── sniff.dat
├── system.cfg -> ../../mc2srcdata/build_scripts/system.cfg
├── textures.fst -> ../../mc2srcdata/build_scripts/textures.fst
└── tgl.fst -> ../../mc2srcdata/build_scripts/tgl.fst
```

The game launches. I try to load the Carver 5 campaign. Then texture issues arise.

I am trying to resolve missing texture files. Slowly I am finding which are missing, but I think something else might be wrong.

The message on the console:
```
MSGBOX: MechCommander 2 could not open the file data/textures/mc2_01.water0016.tga.
Please insert the MechCommander 2 CD, and then click 
OK to continue. : MechCommander 2 CD Not Inserted
```

Even though they are texture files, and it doesn't matter what it looks like, I am replacing them with copies of other texture data. Still, there are many I am either not generating, or are missing.

After `cp data/textures/mc2_01.water0015.tga  data/textures/mc2_01.water0016.tga` Some time later...

`MSGBOX: MechCommander 2 could not open the file data/textures/mc2_01.water0017.tga.`

OK...I will make them up to 99.
```
for i in `seq 17 99`
do
    cp data/textures/mc2_01.water0015.tga  data/textures/mc2_01.water00${i}.tga
done
```

`MSGBOX: MechCommander 2 could not open the file data/textures/mc2_01.water0100.tga.`

!
OK. 1000!
```
for i in `seq 100 999`
do
    cp data/textures/mc2_01.water0015.tga  data/textures/mc2_01.water0${i}.tga
done
```

New missing texture data
```
MSGBOX: MechCommander 2 could not open the file data/textures/mc2_01.burnin.jpg.
```

Looking at the available files, there is a `data/textures/mc2_01.burnin.tga`, but the code does not consider it and skips to CD checking code. 

Try loading the training campaign instead, same issues coming back.
```
MSGBOX: MechCommander 2 could not open the file data/textures/tut_01.water0010.tga.
Please insert the MechCommander 2 CD, and then click 
OK to continue. : MechCommander 2 CD Not Inserted
```

Also missing from training campaign:
```
textures/tut_01.lst
```

I believe there are pieces missing. e.g
```
$ find . -iname 'tut*lst'
./tut_05.lst
./tut_03.lst
``` 
I was also looking at the Windows Game installation and CD, but they don't have individual texture files. 

I have attached the textures files I have on my system (merging the two texture folders) 
```
$ cd mc2srcdata/textures 
$ tree
... see file for data ...
5 directories, 1397 files
```
[texture_tree.txt](https://github.com/alariq/mc2srcdata/files/5641575/texture_tree.txt)

Are there files missing from the Linux build process? any help would be appreciated.

Thanks!

**Comment by VielLosero** [comment]
Same issue here :(

**Comment by RolandHeath** [comment]
Dug into this a bit tonight (and a little into the morning) and found that I can fix it by changing MAX_WATER_DETAIL_TEXTURES in terrtxm2.h (from 256 down to 16, in my test). 

I'm guessing there's a similar max for the burning animations, and possibly others... but I've got no idea if there's larger implications of fiddling with them.

**Comment by RolandHeath** [comment]
Ok... also found a workaround for the burnin.jpg problem. It's an ugly solution, I just open the associated burnin.tga with an image editor (e.g. gimp or pinta) and then saved it as a .jpg. 
There's still display issues, but the game was playable after that.

**Comment by alariq** [comment]
Hi, guys.
I'll try to have a look. Linux is my main dev environment so everything should be ok, maybe it is indeed issue with some missing files on GH. Though I see there is a mention that original game does not have loose files. Indeed it uses packs, so does my version. Please make sure the build tool has generated a pack files (.fst)

**Comment by RolandHeath** [comment]
I have the following .fst files:
art.fst
camera.fst
effect.fst
insignia.fst
misc.fst
mission.fst
textures.fst
tgl.fst
In light of that... I'm wondering if maybe we're not dropping them into the right place. These were in the root directory alongside the executable, but I'm guessing they probably belong in data/

If we're lucky, this could just be a documentation issue.

**Comment by alariq** [comment]
yes they should go to the root directory (same level as binary, basically same as in original game)

**Comment by alariq** [comment]
I think I've found an issue related to "Please insert the MechCommander 2 CD". one of the .fst files is corrupted when generated by a tool, I'll check what is the problem and get back to you. WIll also update the documentation.

**Comment by alariq** [comment]
finally figured out what the problem was. Apparently, make substituted `*.tgl` and other params for a `makersp` tool for actual files :-)
Edit: also updated a README.md in `build_scripts` folder to make it more clear
